{
    "ignore": [
        "^connPFM/tests/.*",
        "^connPFM/due.py.*",
        "^connPFM/_version.py.*",
        "^connPFM/info.py.*",
        "^connPFM/deconvolution/stability_lars_caller.py"
    ],
    "codecov": {
        "notify": {},
        "require_ci_to_pass": true
    },
    "coverage": {
        "status": {
            "patch": {
                "default": {
                    "target": 0,
                    "threshold": 0
                }
            },
            "project": {
                "default": {
                    "target": 0,
                    "threshold": 0
                }
            }
        }
    }
}